# database connection configuration
db:
  host: postgres
  port: 5432
  database: port
  user: postgres
  password: 'e72a7e3456874163b3b715297be8a731'
  dialect: postgres

# default login configuration
defaultGroup:
  mixin: true
  keystore: true
  anonymous: true
  metamask: true

# admin user eth addresses
admin:
  - '0xffffffffffffffffffffffffffffffffffffffff'

joinBySeedUrl: false
